[package]
name = "crabe_io"
version = "0.1.0"
edition = "2021"
authors = ["NAMeC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.11.8"
bytes= "1.4"
log = "0.4.17"
clap = { version = "4.1.8", features = ["derive"] }
crabe_protocol = { path = "../crabe_protocol" }
crabe_framework = { path = "../crabe_framework" }
flume = "0.10.14"
tokio = { version = "1.25.0", features = ["full"] }
tungstenite = "0.18.0"
futures-util = "0.3.26"
tokio-tungstenite = "0.18.0"
serde = { version= "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
uom = { version = "0.34.0", features = ["use_serde"] }
serialport = "4.2.0"